### ISSUE TITLE
Pushpop-slack trigger

### ISSUE THREAD

**Issue by josephwegner** [pushpop-project/pushpop#11]
We should be able to use the new Pushpop webhook support to tie in to Slack's Outgoing Webhooks. This would make for a pretty solid trigger - on the Slack end you can define specific trigger words, and then all you have to give to Pushpop is the URL.

**Comment by josephwegner** [comment]
So, it actually doesn't make any sense to use the webhook integration _inside_ of pushpop-slack... We can't programmatically make slack outgoing webhooks, and there's no way I'm building a websocket thing for real-time updates, so all we would be doing is aliasing `webhook` to `slack_outgoing`.

However, we could poll their API for certain things... For instance, we could look at the `file` API for any files that have been created in the last `period`. Or do a similar thing for chat messages.

However, that's a fair bit of work for a lot of functionality that would be accomplished if the user just set up an outgoing webhook. @hex337 @tushdante what do you guys think? Personally I think this isn't valuable enough to justify the time.

**Comment by hex337** [comment]
I agree. Probably not really any good triggers for this, I think 99% of the value comes from actions.
