### ISSUE TITLE
Mixpanel triggers/actions

### ISSUE THREAD

**Issue by josephwegner** [pushpop-project/pushpop#13]
Mixpanel is obviously good at tracking, but they also have a surprisingly good querying API. They have a [ruby client](https://github.com/keolo/mixpanel_client) that should make constructing the queries a bit easier.

I would say, as much as possible, the mixpanel integration should meet feature parity with the Keen integration.

**Comment by hex337** [comment]
Yes, this would be awesome.

**Comment by josephwegner** [comment]
This is a thing! https://github.com/pushpop-project/pushpop-mixpanel

**Comment by josephwegner** [comment]
Doneski
