### ISSUE TITLE
List for 3rd party pushpop gems

### ISSUE THREAD

**Issue by willbarrett** [pushpop-project/pushpop#22]
Hey Pushpop folks!

I made a pushpop plugin! You can find the source here: https://github.com/willbarrett/pushpop-github-status

I'm working on a project that will require creating quite a few more plugins. Any chance we could get a 3rd party plugin list going? I'm happy to do the work if the maintainers think it's worthwhile? Maybe an addition to the README?

Will

**Comment by josephwegner** [comment]
YES! it's totally worthwhile.

 If you want it in the README, totally PR it in and I'll merge it.

It may also make sense as a wiki item... Not sure if you can do those without permissions. If you think wiki > README, let me know and I'll get that started.

**Comment by willbarrett** [comment]
I'll open a PR for the README - I figure that's as good a place as any for it to start. If it gets to be too much, I figure we can split it into a wiki page later?

**Comment by josephwegner** [comment]
Yep, agreed.
