### ISSUE TITLE
Already initialized constant when loading Keen / Sendgrid plugins

### ISSUE THREAD

**Issue by jfeldstein** [pushpop-project/pushpop#3]
jordans-mbp:pushpop-keen-cacher jordan$ foreman run bundle exec rake jobs:run_once[jobs/MAUAndEngagementJob.rb]
    /Users/jordan/.rvm/gems/ruby-2.0.0-p353/gems/pushpop-keen-0.1.1/lib/pushpop-keen.rb:8: warning: already initialized constant Pushpop::Keen::PLUGIN_NAME
    /Users/jordan/.rvm/gems/ruby-2.0.0-p353/gems/pushpop-0.1.0/lib/plugins/keen.rb:7: warning: previous definition of PLUGIN_NAME was here
    /Users/jordan/.rvm/gems/ruby-2.0.0-p353/gems/pushpop-sendgrid-0.1.2/lib/pushpop-sendgrid.rb:18: warning: already initialized constant Pushpop::Sendgrid::PLUGIN_NAME
    /Users/jordan/.rvm/gems/ruby-2.0.0-p353/gems/pushpop-0.1.0/lib/plugins/sendgrid.rb:17: warning: previous definition of PLUGIN_NAME was here

Any idea why these would say that?

**Comment by josephwegner** [comment]
@jfeldstein were you able to resolve your issue?

**Comment by josephwegner** [comment]
Closing this. Feel free to reopen if your issue persists.
